### ISSUE TITLE
which MySQL version is appropriate

### ISSUE THREAD

**Issue by mayupsc** [apetkau/orthomcl-pipeline#23]
DBD::mysql::st execute failed: The used command is not allowed with this MySQL version at /home/galaxy/Downloads/orthomclSoftware-v2.0.9/bin/orthomclLoadBlast line 39, <F> line 12.

**Comment by apetkau** [comment]
I believe this issue is described in the original OrthoMCL documentation (see https://github.com/apetkau/orthomclsoftware-custom/blob/master/doc/OrthoMCLEngine/Main/UserGuide.txt#L320).  Could you try out the suggestions listed their?  Mainly, I believe you will need to enable the `local_infile` system variable (https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_local_infile).

**Comment by apetkau** [comment]
I am closing this issue. If it's still a problem please re-open.
